language: c
os: osx
osx_image: xcode8.3

env:
  global:
    - CODECOV_TOKEN=a725e35c-a6da-400e-a56f-ae7b630fc3b2

jobs:
  include:
    - stage: compile
      script: make
    - stage: norminette+
      script: make test_norm
    - stage: codecov
      script: make test_coverage && bash <(curl -s https://codecov.io/bash)
