language: c

env:
  global:
    - CODECOV_TOKEN=a725e35c-a6da-400e-a56f-ae7b630fc3b2

jobs:
  include:
    - stage: compile
      os: osx
      osx_image: xcode8.3
      script: make
    - stage: norminette+
      os: linux
      script: make test_norm
    - stage: tests
      os: osx
      osx_image: xcode8.3
      script: make test
    - stage: codecov
      os: osx
      osx_image: xcode8.3
      script: make test_coverage && bash <(curl -s https://codecov.io/bash)
