name: 42sh tests

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04, ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - name: run norminette+
      run: make test_norm
    - name: install criterion macOS
      if: matrix.os == 'macOS-10.14'
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install snaipe/soft/criterion
    - name: make test_coverage macOS
      if: matrix.os == 'macOS-10.14'
      run: make test_coverage
    - name: upload coverage tot codecov.io macOS
      if: matrix.os == 'macOS-10.14'
      run: bash <(curl -s https://codecov.io/bash) -t a725e35c-a6da-400e-a56f-ae7b630fc3b2
    - name: install criterion linux
      if: matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-16.04'
      run: |
        sudo add-apt-repository -y ppa:snaipewastaken/ppa
        sudo apt-get update
        sudo apt-get install -y libncurses5-dev
        sudo apt-get install -y criterion-dev
    - name: run tests linux
      if: matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-16.04'
      run: make test
