name: C/C++ CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run tests
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install snaipe/soft/criterion
        make test_coverage
        bash <(curl -s https://codecov.io/bash)
