name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: install criterion
      if: matrix.os == 'macOS-latest'
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install snaipe/soft/criterion
    - name: run test and make coverage
      if: matrix.os == 'macOS-latest'
      run: make test_coverage
    - name: send coverage
      if: matrix.os == 'macOS-latest'
      run: bash <(curl -s https://codecov.io/bash)
    - name: install criterion linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo add-apt-repository -y ppa:snaipewastaken/ppa
        sudo apt-get update
        sudo apt-get install -y criterion-dev
    - name: run test linux
      if: matrix.os == 'ubuntu-latest'
      run: make test
